Qt6: don't build tools when cross-compiling by default
Linking against shared libraries appears to have issues, potentially due to mixed native and cross-compiled libs.

[1409/1453] Linking CXX executable qtbase/libexec/rcc
FAILED: qtbase/libexec/rcc
: && /usr/bin/aarch64-linux-gnu-g++-13 -DNDEBUG -O2 -Wl,-z,relro,-z,now -Wl,--enable-new-dtags -fPIE -pie qtbase/src/tools/rcc/CMakeFiles/rcc_native.dir/rcc_native_autogen/mocs_compilation.cpp.o qtbase/src/tools/rcc/CMakeFiles/rcc_native.dir/main.cpp.o qtbase/src/tools/rcc/CMakeFiles/rcc_native.dir/rcc.cpp.o -o qtbase/libexec/rcc  -Wl,-rpath,/home/user/.conan2/p/b/qtc8d3483cfcb1b/b/build/Release/qtbase/lib:  qtbase/lib/libQt6Core.so.6.8.2 && :
/usr/lib/gcc-cross/aarch64-linux-gnu/13/../../../../aarch64-linux-gnu/bin/ld: warning: libicudata.so.75, needed by /home/user/.conan2/p/b/icu9b438096da10d/p/lib/libicuuc.so.75, not found (try using -rpath or -rpath-link)
/usr/lib/gcc-cross/aarch64-linux-gnu/13/../../../../aarch64-linux-gnu/bin/ld: /home/user/.conan2/p/b/icu9b438096da10d/p/lib/libicuuc.so.75: undefined reference to `icudt75_dat'
collect2: error: ld returned 1 exit status