fbgemm: test with asmjit:shared=False
Looks like it might be causing test_package failures for Clang:

libfbgemm.so: undefined reference to __gnu_h2f_ieee